biojppm/c4core

src/c4/substr.hpp

on linux `ioctl-types.h` defines NCC, which clashes with the NCC typedef
for non const char. we therefore rename NCC to NCC_

substr: resolve name clash with `ioctl-types.h`

---

src/c4/base64.cpp

Hi,
thanks for your work on rapidyaml.
The following change fixes narrowing conversions from int to char, which according to the C++ standard makes the program ill formed and causes build fails on some platforms. 
The failure can be reproduced for example with g++ 8.3.0 for ARM.
With this fix the build succeeds.
--Matus

Fix of int to char narrowing conversion error

---

src/c4/charconv.hpp

Hey!
I've just found your library for parsing YAML files after getting tired of waiting 10 seconds to parse a 20mb YAML file with some _other_ library and been trying to build this on Clang C++20 with Microsoft STL, but ran into this issue where `enum class chars_format` is not strictly char so it ends up breaking this static assert (since `sizeof(...)` ends up 16). After the fix it should build for C++20 as well, C++11 was working fine eitherway it seems.
`C4_STATIC_ASSERT(sizeof(fmt) == _FTOA_COUNT);`
P.S. I had to include the `<iterator>` header for `std::size`, not sure if the changes fit the coding style of this repo since I've just cloned it so my apologies if it doesn't.

Fixing charconv static assert for Microsoft STL C++20. 

---

appveyor.yml
src/c4/language.hpp
src/c4/types.hpp
test/test_charconv.cpp

compile C++20 in msvc

---

src/c4/error.cpp

for some reason, atoi isn't resolved preporly for me:
```
/home/tim/dev/rapidyaml/ext/c4core/src/c4/error.cpp: In function ‘bool c4::is_debugger_attached()’:
/home/tim/dev/rapidyaml/ext/c4core/src/c4/error.cpp:167:78: error: no matching function for call to ‘atoi(char*)’
167 |                 first_call_result = !!atoi(tracer_pid + sizeof(TracerPid) - 1);
|                                                                              ^
In file included from /home/tim/dev/rapidyaml/src/c4/yml/././tree.hpp:10,
from /home/tim/dev/rapidyaml/src/c4/yml/./emit.hpp:9,
from /home/tim/dev/rapidyaml/src/c4/yml/emit.def.hpp:5,
from gp/rapidyaml.cpp:2:
/home/tim/dev/rapidyaml/ext/c4core/src/c4/charconv.hpp:481:6: note: candidate: ‘template<class T> bool c4::atoi(c4::csubstr, T*)’
481 | bool …
```

fix atoi resolution in gcc

---

src/c4/cpu.hpp
src/c4/windows_push.hpp

According to [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros), `_WIN32` and `_WIN64` macros does not mean it's x86 or x64, it maybe ARM or ARM64.
The fast_float also has to update. (https://github.com/fastfloat/fast_float/pull/80)

fix: build error on windows arm/arm64

---

src/c4/cpu.hpp
test/test_base64.cpp

Added CPU detection macros based on https://sourceforge.net/p/predef/wiki/Architectures/.
I also fixed the Base64 tests, which did not have correct expected outputs for integer representations on big-endian architectures. There are several ways to handle this, and I picked an obvious one. If you prefer a different approach, I am happy to revise the details.
These changes are useful for Fedora since `s390x` (Linux on Z) is a supported primary architecture.

Support z/Architecture (s390x)

---

src/c4/platform.hpp
src/c4/time.cpp

[fix] make currtime() work on POSIX systems other than Linux

---

.github/workflows/test.yml
CMakeLists.txt
src/c4/charconv.hpp

I actually missed a small change I made locally when creating #42, which I only now realized after upgrading to rapidyaml 0.2.3. This PR updates my previous fix for C4CORE_NO_FAST_FLOAT builds.

[fix] fix build with C4CORE_NO_FAST_FLOAT (previous fix was incomplete)

---

changelog/current.md

[fix] re #53: add install exports

---

src/c4/windows.hpp

This fix cross build from Linux with mingw

Fix windows include on case-sensitive filesystem

---

changelog/current.md
src/c4/charconv.hpp
src/c4/substr.hpp
test/test_charconv.cpp
test/test_substr.cpp

[fix] accept infinity, inf and nan as real numbers

---

src/c4/cpu.hpp

Since https://github.com/uraimo/run-on-arch-action doesn't support riscv currently, I'm not adding any test. I will try hard to add support for it.

[impl] add riscv cpu support

---

.github/reqs.sh
.github/workflows/test.yml
CMakeLists.txt
changelog/current.md
compat.cmake
src/c4/charconv.hpp
src/c4/compat/gcc-4.8.hpp
src/c4/compiler.hpp
test/test_allocator.cpp
test/test_error.cpp
tools/amalgamate.py

- Add polyfills for missing stl templates
- some move related type_traits are not available as builtins, support is dropped
- disable broken -Wshadow
- disable sanitize and benchmark features when old compiler is detected (both require recent compilers)
Note: no modifications will be required on cmake repo, it felt better to add a repo specific CMake file here, and modification on gtest were adding flags in global scope anyway (the -include are not needed to compile c4core itself).
I ran tests on Github (coverage fails du to missing creds) and ensure header was present in amalgamated version.

:wrench: gcc-4.8.5 support

---

src/c4/std/vector_fwd.hpp

This fixes Android NDK build which uses `__ndk1` namespace. And probably dozen other build systems where custom tags are used.

[fix] properly supporty libc++ ABI namespaces

---

bm/bm_charconv.cpp
src/c4/charconv.hpp
src/c4/format.hpp
test/test_charconv.cpp
test/test_format.cpp

Rework of https://github.com/biojppm/c4core/pull/75
- added bool overflows<T>(csubstr) function
- added fmt::overflow_checked() formatter
Overhead is 10-15% (when it was more 15-20% with previous implementation), I think overhead on u8 and i8 is more important just because there are more numbers with 3 digits spread on the domain (60%) so it has to compare bytes more often.
Also did not benchmark with hex/oct/bin encodings.
[overflow_checked.json.txt](https://github.com/biojppm/c4core/files/8177287/overflow_checked.json.txt)
I did not add atoi_rc, it felt a bit too much, instead it may be interesting to implement a couple helpers at RapidYaml level (overriding `operator>>`), ex:
```cpp
// on error (overflow included) v will default to "10"
node["test"] >> fmt::default_to(v, 10);
// fetch …
```

Add integer overflow detection feature

---

src/c4/cpu.hpp

c4core fails to build on Debian bookworm/sid for armel as follows.
```
/<<PKGBUILDDIR>>/third_party/rapidyaml/rapidyaml/ext/c4core/src/c4/cpu.hpp:68:13: error: #error "unknown CPU architecture: ARM"
68 | #           error "unknown CPU architecture: ARM"
|             ^~~~~
```
Kindly find the following log for details of the build error:
https://buildd.debian.org/status/fetch.php?pkg=jsonnet&arch=armel&ver=0.18.0%2Bds-1&stamp=1655744320&raw=0
This patch tries to address this issue.
If things are satisfactory, please consider merging this pull request.
Thanks and regards,
Fukui

[fix] fix compile error in armel

---

.github/workflows/emscripten.yml
changelog/current.md
src/c4/substr.hpp
test/test_substr.cpp

Fixes to `csubstr::first_real/int/uint_span()`

---

src/c4/cpu.hpp

When building for our platform got #error "unknown CPU architecture: ARM"
The fully qualified arm version for our platform  which specifies the FPU is __ARM_ARCH_7EM__
$ echo | arm-none-eabi-gcc -dM -E -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 - | grep ARCH
#define __ARM_ARCH_PROFILE 77
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 7
#define __ARM_ARCH_7EM__ 1
#define __ARM_ARCH_EXT_IDIV__ 1
This was missing in cpu.hpp, hence the PR.

Adds missing fully qualified arm arch version.

---

src/c4/platform.hpp

Please see the full commit messages for details. This (ratther oddly) fixes failure to compile on the ppc64le version of Red Hat Enterprise Linux 8.
The `__unix__` change is just for completeness/symmetry.

Better predefined macros for platform detection

---

src/c4/cpu.hpp

There is a missing check for __ARM_ARCH_6KZ__.

Fix build on FreeBSD/armv6

---

CMakeLists.txt
changelog/current.md
src/c4/std/std.hpp
src/c4/std/string.hpp
src/c4/std/string_view.hpp
src/c4/substr.hpp
test/test_format.cpp
test/test_std_string.cpp
test/test_substr.cpp
tools/amalgamate.py

substr: cleanup constructors, add interop with std::string_view

---

src/c4/std/vector_fwd.hpp

libstdc++ has a special debug mode, which is enabled by #define-ing _GLIBCXX_DEBUG. In this mode std::vector is actually std::__debug::vector. Adjust the vector forward declaration to make the code build when _GLIBCXX_DEBUG is defined.
This is needed to build rapidyaml together with _GLIBCXX_DEBUG.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html for some details on _GLIBCXX_DEBUG.

Support _GLIBCXX_DEBUG

---

CMakeLists.txt
changelog/current.md
src/c4/gcc-4.8.hpp
tools/amalgamate.py

re #103
This duplicates the gcc 4.8 compat header. It's a good-enough trade-off for the fact that it needs to be installed, and not having `c4_add_target()` add the include dir. The header contents are stable enough to withstand the duplication from the cmake project (which is needed because gtest does not compile on 4.8 without this header being injected with `-include`).

[fix] ensure gcc 4.8 compat header is installed

---

changelog/current.md
src/c4/memory_resource.cpp

Concerning the issue : [#127](https://github.com/biojppm/c4core/issues/127)
memalign was added for Android API since version 16. Adding this permits us to build c4core in android_armv8 and android_x86_64.

[update] add Android support for API 16+

---

src/c4/cpu.hpp

LoongArch is a new architecture that is already supported by linux-6.1, gcc-12, and I want to add LoongArch support for c4core.

Add LoongArch cpu support.

---

src/c4/compiler.hpp

Thanks for providing such a very fast libraries!
In mingw64 compiler, there are compilation errors on rapidyaml 0.7.0:
```
In file included from src/c4/yml/tree.hpp:12,
from src/c4/yml/reference_resolver.hpp:4,
from src/c4/yml/reference_resolver.cpp:1:
src/c4/yml/common.hpp:14:10: fatal error: alloca.h: No such file or directory
14 | #include <alloca.h>
|          ^~~~~~~~~~
compilation terminated.
```
This is due to the lack of `alloca.h` in the mingw compiler as well as in the MSVC compiler.
I want to add `C4_MINGW` macro to c4core so that rapidyaml uses malloc.h instead of alloca.h on mingw.
```
#if defined(C4_MSVC) || defined(C4_MINGW)
#include <malloc.h>
#else
#include <alloca.h>
#endif
```
This same fix is also implemented in imgui.
https://github.com/ocornut/imgui/issues/276

Please add C4_MINGW macro for rapidyaml 0.7.0

---

src/c4/enum.hpp

https://en.cppreference.com/w/cpp/types/ptrdiff_t shows this is defined in <cstddef> but that header is not directly included in this file.

Add #include <cstddef> for std::ptrdiff_t usage

---

.gitmodules

Missing default branches causes fails if the project is imported through CMake's `FetchContent` mechanism. It checks out the default branch and then switches to the pinned SHA. If the default branch is not specified, it assumes "origin/master", which doesn't always exist.
Here's the fail that I observe:
```
Submodule path 'ext/c4core/cmake': checked out 'e87e11f1a10af8aab4e0ceaade0bc7807f207eb1'
Submodule path 'ext/c4core/src/c4/ext/debugbreak': checked out '328e4abca3384cbd0a69e70f263cc7b2794bff09'
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'src/c4/ext/fast_float'
```
The issue is reproduced only with relatively old git, for example with the one that come with Ubuntu 20.04.

Specify default branch for git submodules.
